### ISSUE TITLE
[1.16.5] Error when adding mod to server

### ISSUE THREAD

**Issue by JoshForce** [LimonBlaze/origins-accessibilities#4]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
Whenever I add the mod to my server I get the following message
-- Head --
Thread: main
Stacktrace:
	at dev.limonblaze.oriacs.common.item.UmbrellaItem.<clinit>(UmbrellaItem.java:31) ~[oriacs:0.999] {re:mixin,re:classloading}
-- MOD oriacs --
Details:
	Mod File: origins-accessbilities-1.16.5-0.999.jar
	Failure message: Origins: Accessibilities (oriacs) has failed to load correctly
		java.lang.NoSuchMethodError: net.minecraft.util.math.MathHelper.func_180183_b(FFF)I
	Mod Version: 0.999
	Mod Issue URL: https://github.com/LimonBlaze/origins-accessibilities/issues
	Exception message: java.lang.NoSuchMethodError: net.minecraft.util.math.MathHelper.func_180183_b(FFF)I

**Steps to reproduce:**
This can be reproduced at any time by adding the jar file to the mods folder on a server.

The log can be found here:
[crash-2023-01-10_02.36.57-fml.txt](https://github.com/LimonBlaze/origins-accessibilities/files/10378514/crash-2023-01-10_02.36.57-fml.txt)

**Mod list:**
Mod List: 
		forge-1.16.5-36.2.35-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		origins-accessbilities-1.16.5-0.999.jar           |Origins: Accessibilities      |oriacs                        |0.999               |ERROR     |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.153.jar                          |Just Enough Items             |jei                           |7.7.1.153           |CREATE_REG|Manifest: NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.2.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.2      |CREATE_REG|Manifest: NOSIGNATURE
		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |CREATE_REG|Manifest: NOSIGNATURE
		steampowered-1.16.5-1.2.6.jar                     |Create: Steam Powered         |steampowered                  |1.16.5-1.2.6        |CREATE_REG|Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.3.jar                         |Patchouli                     |patchouli                     |1.16.4-53.3         |CREATE_REG|Manifest: NOSIGNATURE
		Origins-1.16.5-0.7.3.9-forge.jar                  |Origins                       |origins                       |0.7.3.9             |CREATE_REG|Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2g.jar                       |Create                        |create                        |v0.3.2g             |CREATE_REG|Manifest: NOSIGNATURE
		createdeco-1.1.2-1.16.5.jar                       |Create Deco                   |createdeco                    |1.1.2-1.16.5        |CREATE_REG|Manifest: NOSIGNATURE
		createautomated-1.16.5-1.4.1a.jar                 |Create Automated              |createautomated               |1.16.5-1.4.1a       |CREATE_REG|Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.4.jar                        |Waystones                     |waystones                     |7.6.4               |CREATE_REG|Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.5p6.jar                     |Journeymap                    |journeymap                    |5.8.5p6             |CREATE_REG|Manifest: NOSIGNATURE
		Placebo-1.16.5-4.7.0.jar                          |Placebo                       |placebo                       |4.7.0               |CREATE_REG|Manifest: NOSIGNATURE
		createpixelmon-1.16.5-1.0.3.jar                   |Create: Pixelmon              |createpixelmon                |1.16.5-1.0.3        |CREATE_REG|Manifest: NOSIGNATURE
		NaturesCompass-1.16.5-1.9.1-forge.jar             |Nature's Compass              |naturescompass                |1.16.5-1.9.1-forge  |CREATE_REG|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.4.32.jar                |Bookshelf                     |bookshelf                     |10.4.32             |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		EnchantmentDescriptions-1.16.5-7.1.20.jar         |EnchantmentDescriptions       |enchdesc                      |7.1.20              |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		create-confectionery1.16.5_v1.0.2.jar             |Create Confectionery          |create_confectionery          |1.0.2               |CREATE_REG|Manifest: NOSIGNATURE
		fancymenu_forge_2.12.9_MC_1.16.2-1.16.5.jar       |FancyMenu                     |fancymenu                     |2.12.9              |CREATE_REG|Manifest: NOSIGNATURE
		Apotheosis-1.16.5-4.8.9A0.jar                     |Apotheosis                    |apotheosis                    |4.8.9A0             |CREATE_REG|Manifest: NOSIGNATURE
		architectury-1.32.66.jar                          |Architectury                  |architectury                  |1.32.66             |CREATE_REG|Manifest: NOSIGNATURE
		cloth-config-4.16.91-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.16.91             |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.35-universal.jar                |Forge                         |forge                         |36.2.35             |CREATE_REG|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Disenchanting-forge-1.16.5-1.7.2.jar              |Disenchanting                 |disenchanting                 |1.6.0               |CREATE_REG|Manifest: NOSIGNATURE
		valhelsia_core-16.0.15.jar                        |Valhelsia Core                |valhelsia_core                |16.0.15             |CREATE_REG|Manifest: NOSIGNATURE
		forbidden_arcanus-16.2.3.jar                      |Forbidden & Arcanus           |forbidden_arcanus             |16.2.3              |CREATE_REG|Manifest: NOSIGNATURE
		konkrete_forge_1.5.3-1_MC_1.16.2-1.16.5.jar       |Konkrete                      |konkrete                      |1.5.3               |CREATE_REG|Manifest: NOSIGNATURE
		createaddition-1.16.5-20220129a.jar               |Create Crafts & Additions     |createaddition                |1.16.5-20220129a    |CREATE_REG|Manifest: NOSIGNATURE
		Pixelmon-1.16.5-9.1.0-server.jar                  |Pixelmon Mod                  |pixelmon                      |9.1.0               |CREATE_REG|Manifest: NOSIGNATURE
		ExplorersCompass-1.16.5-1.1.2-forge.jar           |Explorer's Compass            |explorerscompass              |1.16.5-1.1.2-forge  |CREATE_REG|Manifest: NOSIGNATURE
		byg-1.3.5.jar                                     |Oh The Biomes You'll Go       |byg                           |1.3.4               |CREATE_REG|Manifest: NOSIGNATURE

**Comment by JoshForce** [comment]
I should mention umbrella's didn't appear to work in client side of mod either on a singleplayer world in 1.16.5

**Comment by MarbleGateKeeper** [comment]
Fixed in 0.9991
